# Generated by Django 4.0 on 2021-12-16 19:54

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields

import api.authentication.helpers.secrets


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=api.authentication.helpers.secrets.generate_code,
                        max_length=6,
                        verbose_name="Code",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("RESET_PASSWORD_REQUEST", "RESET_PASSWORD_REQUEST"),
                            ("USER_CONFIRMATION", "USER_CONFIRMATION"),
                        ],
                        max_length=25,
                        verbose_name="Type",
                    ),
                ),
                (
                    "was_used",
                    models.BooleanField(
                        default=False, verbose_name="Was already used?"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_tokens",
                        to="authentication.user",
                        verbose_name="The User which is associated to this",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code",
                "ordering": ("-created",),
            },
        ),
    ]
